services:
  - name: flask-backend
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString

databases:
  - name: postgres-db
    plan: free
    postgresVersion: 15
