"""Ajoute ListeCourses et corrige relation

Revision ID: 5994e1f32397
Revises: 5a80873d8de3
Create Date: 2025-03-13 00:00:15.008935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5994e1f32397'
down_revision = '5a80873d8de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unite', sa.String(length=20), nullable=True))
        batch_op.drop_column('unite_par_defaut')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unite_par_defaut', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('unite')

    # ### end Alembic commands ###
