"""Ajoute ListeCourses et corrige relation

Revision ID: 5a80873d8de3
Revises: e2733437b718
Create Date: 2025-03-11 16:38:04.430074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a80873d8de3'
down_revision = 'e2733437b718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapes',
    sa.Column('id_etape', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_recette', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_recette'], ['recettes.id_recette'], ),
    sa.PrimaryKeyConstraint('id_etape')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etapes')
    # ### end Alembic commands ###
