"""Ajout de la colonne id_inventaire à liste_courses

Revision ID: 719034612fd3
Revises: a98f6a429bb3
Create Date: 2025-03-13 14:24:48.978308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719034612fd3'
down_revision = 'a98f6a429bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('ingredients_id_utilisateur_fkey', type_='foreignkey')
        batch_op.drop_column('publique')
        batch_op.drop_column('id_utilisateur')

    with op.batch_alter_table('liste_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_inventaire', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'inventaires', ['id_inventaire'], ['id_inventaire'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liste_courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_inventaire')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_utilisateur', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('publique', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('ingredients_id_utilisateur_fkey', 'utilisateurs', ['id_utilisateur'], ['id_utilisateur'])

    # ### end Alembic commands ###
